title: 软件充满了魔法，我想成为最会玩的那个
email: aoingl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  算法学习, 系统架构, 开源软件
baseurl: ""
url: "ihomeland.org"
twitter_username: aoingl
github_username:  gaol

# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-cayman

destination: ./_site
exclude: []
timezone: Asia/Shanghai
encoding: UTF-8
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
