name: 议事堂
title: 书山有路勤为径，学海无涯苦作舟
subtitle: >
 <p>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 &nbsp;&nbsp;&nbsp; 理无专在, 学无止境 <br/>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
     - 清朝刘开《问说》</p>
email: aoingl#gmail.com
keywords: 读书杂谈,程序员修炼
description: >
 理无专在, 学无止境
baseurl: ""
url: "ihomeland.org"
twitter_username: aoingl
github_username:  gaol

# Build settings
markdown: kramdown

destination: ./_site
exclude: []
timezone: Asia/Shanghai
encoding: UTF-8
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 10
paginate_path: "/page:num"

