baseURL: "http://example.org/"
theme: "hugo-coder"
paginate: 20
canonifyurls: true
languagecode: "zh-cn"
defaultcontentlanguage: "zh-cn"
defaultContentLanguageInSubdir: true

pygmentsstyle: "b2"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

params:
  email: "aoingl@gmail.com"
  footercontent: "Be a good man and enjoy the life!"
  colorscheme: auto
  hidecredits: false
  hidecopyright: false
  math: true
  custom_css: ["css/base16.dark.css", "css/prism.css", "css/main.css"]
  favicon_32: "/images/favicon-32x32.png"
  favicon_16: "/images/favicon-16x16.png"

  social:
    - name: "Github"
      icon: "fab fa-github"
      weight: 1
      url: "https://github.com/gaol/"
      target: "_blank"
    - name: "Weibo"
      icon: "fab fa-weibo"
      weight: 2
      url: "https://weibo.com/aoingl"
      target: "_blank"
    - name: "Twitter"
      icon: "fab fa-twitter"
      weight: 3
      url: "https://twitter.com/aoingl"
      target: "_blank"

languages:
  zh-cn:
    author: "双木为琳"
    languagename: "中文"
    title: "Lin' 博客"
    contentDir: "content/zh-cn"
    weight: 1
    info: "奇妙的世界"
    description: "我的博客网站"
    keywords: "博客,开发,个人"
    avatarurl: "images/avatar.svg"
    menu:
      main:
        - name: "博客"
          url: "/zh-cn/posts"
          weight: 1

        - name: "关于"
          url: "/zh-cn/about"
          weight: 2
  en:
    author: "Lin Gao"
    languagename: "English"
    contentDir: "content/en"
    title: "Lin's Blog"
    gravatar: "aoingl@gmail.com"
    weight: 2
    info: "wonderful world"
    description: "Lin's blog"
    keywords: "blog, developer, personal"
    menu:
      main:
        - name: "Blog"
          url: "/en/posts"
          weight: 1

        - name: "About"
          url: "/en/about"
          weight: 2

taxonomies:
  category: "categories"
  series: "series"
  tags: "tags"
