---
title: "Using GitHub Actions to set up workflow"
date: 2020-03-26T12:12:06+08:00
draft: false
categories:
  - github
---
= Using GitHub Actions to set up workflow
Lin Gao <aoingl@gmail.com>
v1.0, 2020-03-26: initial version
:source-highlighter: rouge
:rouge-style: base16.dark
:icons: font

In Software Development Lifecycle(SDL), we need a workflow to build, test, package and deliver our projects to a certain platform. Github Actions provides a solution to define that workflow in the repository itself by a yaml file.

== What is github action

Github action is the smallest execution unit to compose a workflow. There are 2 types of github action according to how it is implemented:

* JavaScript action
* docker container action

All actions are executed in a `job` (as `step`s) which is defined in a `workflow`. Each `job` is executed on a `runner` which is actually a virtual machine(VM) comes from AZure cloud(in case of github hosted runners). All `job`s in the workflows are executed in parallel by default unless you define the `needs` to specify the dependency relationship between other jobs. A `job` contains at least one `step`, each `step` is either a command or a github action, they are executed in sequence in the definition order.

== How to define workflow

* using a template
* create the `.github/workflows/some-workflow-name.yml` file directly


