name: Generate Static Site on master branch
on:
  push:
    branches:
    - source

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Ruby Dev
      run: sudo apt-get install ruby-dev

    - name: Install AsciiDoctor plugins
      run: sudo gem install asciidoctor rouge

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.67.0'

    - name: Build by hugo minify
      run: hugo --minify

    - name: Deploy to master branch for user's repository
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: master
        publish_dir: public
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public

